# .github/workflows/ci.yml

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Put back the git branch into git (Earthly uses it for tagging)
      run: |
        branch=""
        if [ -n "$GITHUB_HEAD_REF" ]; then
          branch="$GITHUB_HEAD_REF"
        else
          branch="${GITHUB_REF##*/}"
        fi
        git checkout -b "$branch" || true
        
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.EARTHLY_TOKEN }}
        
    - name: Setup Earthly
      if: ${{ inputs.container_version == null }}
      uses: earthly/actions-setup@v1
      
    - name: Earthly version
      run: earthly --version
      
    - name: Run build
      run: earthly --allow-privileged --ci --push --remote-cache=ghcr.io/jgibbarduk/earthly-example:cache +build-all

